### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chrom** [knownsec/Pocsuite#138]
`pocsuite --url https://www.mysite.com/ --vul-keyword 'magento'  --verify --report ./report.html                                                                               

                              ,--. ,--.
 ,---. ,---. ,---.,---.,--.,--`--,-'  '-.,---.  {2.0.6-nongit-20170922}
| .-. | .-. | .--(  .-'|  ||  ,--'-.  .-| .-. :
| '-' ' '-' \ `--.-'  `'  ''  |  | |  | \   --.
|  |-' `---' `---`----' `----'`--' `--'  `----'
`--'                                            http://pocsuite.org

[!] legal disclaimer: Usage of pocsuite for attacking targets without prior mutual consent is illegal.

[*] starting at 15:46:36

No JSON object could be decoded
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pocsuite/pocsuite_cli.py", line 157, in pcsInit
    if not s.newToken():
  File "/Library/Python/2.7/site-packages/pocsuite/api/x.py", line 107, in newToken
    content = json.loads(req.content)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

**Comment by hysia** [comment]
fixed, you can checkout

**Comment by niubencoolboy** [comment]
I also met this error , have you solved it?

**Comment by niubencoolboy** [comment]
`
[!] legal disclaimer: Usage of pocsuite for attacking targets without prior mutual consent is illegal.

[*] starting at 22:41:33


No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pocsuite-2.0.6-py2.7.egg/pocsuite/pocsuite_cli.py", line 83, in pcsInit
    if z.newToken():
  File "/usr/local/lib/python2.7/dist-packages/pocsuite-2.0.6-py2.7.egg/pocsuite/api/x.py", line 40, in newToken
    content = json.loads(req.content)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

`
