### ISSUE TITLE
pcs-console.py - OSError: [Errno 2] No such file or directory: '/opt/Pocsuite/pocsuite/modules'

### ISSUE THREAD

**Issue by all3g** [knownsec/Pocsuite#5]
We clone code from [respository](https://github.com/knownsec/Pocsuite/),  and run pocsuite console. Some error message as follow:

```
┌─[lab@core]─[/opt/Pocsuite/pocsuite]
└──╼ python pcs-console.py 
Traceback (most recent call last):
  File "pcs-console.py", line 28, in <module>
    initializePoc(folders)
  File "/opt/Pocsuite/pocsuite/lib/core/consoles.py", line 50, in initializePoc
    files = os.listdir(folder)
OSError: [Errno 2] No such file or directory: '/opt/Pocsuite/pocsuite/modules
```
Please create modules directory , or solve the issue in another way.

**Comment by Medicean** [comment]
Please clone the latest respository. We fixed this bug last night.

**Comment by flsf** [comment]
thank you
